.\"
.\" Sccsid @(#)true.1	1.2 (gritter) 6/30/05
.\" Derived from true(1), Unix 7th edition:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.\"
.TH TRUE 1 "7/04/22" "Heirloom Toolchest" "User Commands"
.SH NAME
true, false \- provide truth values
.SH SYNOPSIS
.B true
.PP
.B false
.SH DESCRIPTION
.I True
does nothing, successfully.
.I False
does nothing, unsuccessfully.
They are typically used in input to
.IR  sh (1)
such as:
.PP
	while true
.br
	do
.br
		command
.br
	done
.SH "SEE ALSO"
sh(1)
.SH DIAGNOSTICS
.I True
has exit status zero,
.I false
has a non-zero one.
