.\"
.\" Sccsid @(#)sum.1	1.4 (gritter) 2/14/03
.\" Parts taken from sum(1), Unix 7th edition:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.\"
.TH SUM 1 "2/14/03" "Heirloom Toolchest" "User Commands"
.SH NAME
sum \- sum and count blocks in a file
.SH SYNOPSIS
\fBsum\fR [\fB\-r\fR] [\fIfile\fR]
.SH DESCRIPTION
.I Sum
calculates and prints a 16-bit checksum for the named file,
and also prints the number of blocks in the file.
It is typically used to look for bad spots, or
to validate a file communicated over
some transmission line.
.PP
If the
.B \-r
option is present,
an alternate checksum algorithm is used.
.SH "SEE ALSO"
cksum(1),
wc(1)
.SH DIAGNOSTICS
`Read error'
is indistinguishable from end of file on
most devices; check the block count.
.SH NOTES
The default algorithm is unable
to detect added or missing NUL bytes.
The algorithm selected with
.B \-r
may produce different results in different implementations.
For these reasons,
.IR cksum (1)
should be used in preference.
