.\"
.\" Sccsid @(#)rm.1	1.14 (gritter) 1/24/05
.\" Parts taken from rm(1), Unix 7th edition:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.TH RM 1 "1/24/05" "Heirloom Toolchest" "User Commands"
.SH NAME
rm \- remove directory entries
.SH SYNOPSIS
\fBrm\fR [\fB\-f\&iRr\fR] \fIfile\fR ...
.SH DESCRIPTION
Rm removes the entries
for one or more files from a directory.
If an entry was the last link to the file,
the file is destroyed.
Removal of a file requires write permission in its directory,
but neither read nor write permission on the file itself.
.PP
If a file has no write permission
and the standard input is a terminal,
its permissions are printed
and a line is read from the standard input.
If that line begins with `y'
the file is deleted,
otherwise the file remains.
.PP
When
.B rm
encounters a symbolic link,
the link will be removed,
but its target will remain in the file hierarchy.
.PP
The
.B rm
command accepts the following options:
.TP
.B \-f
No questions are asked
and neither error messages are printed
nor the exit status is affected
in case of nonexistent files.
.B /usr/5bin/rm
and
.B /usr/5bin/s42/rm
will not print an error message
if removal of a file failed.
For
.B /usr/5bin/posix/rm
and
.BR /usr/5bin/posix2001/rm ,
any previous occurrences of the
.B \-i
option are ignored.
.TP
.B \-i
Causes
.B rm
to ask for confirmation
before deleting any file,
and,
unter
.BR \-r ,
whether to examine each directory.
For
.B /usr/5bin/posix/rm
and
.BR /usr/5bin/posix2001/rm ,
any previous occurrences of the
.B \-f
option are ignored.
.TP
.B \-R
Same as
.BR \-r .
This option has been introduced by POSIX.2.
.TP
.B \-r
.B Rm
will recursively delete the entire contents
of directories given as operands,
and the directory itself.
Without this option,
an error comment is printed
if a designated file is a directory.
.SH "ENVIRONMENT VARIABLES"
.TP
.B SYSV3
Causes the text of some messages to be changed.
.SH "SEE ALSO"
rmdir(1),
unlink(2),
rmdir(2)
.SH NOTES
It is forbidden to remove the files `.' and `..'
merely to avoid the antisocial consequences
of inadvertently doing something like `rm \-r .*'.
.PP
With
.B /usr/5bin/rm
and
.BR /usr/5bin/s42/rm ,
a single `\-' can be used to indicate the end of the options list,
as with `rm \- \-file'.
If `\-\-' is used to terminate the options list, though,
a following `\-' will be interpreted as a file name,
so `rm \-\- \-' will remove the file `\-'.
