.\"
.\" Sccsid @(#)tail.1	1.9 (gritter) 12/6/04
.\" Parts taken from tail(1), Unix 7th edition:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.\"
.TH TAIL 1 "12/6/04" "Heirloom Toolchest" "User Commands"
.SH NAME
tail \- deliver the last part of a file
.SH SYNOPSIS
\fBtail\fR [\fB+\fR/\fB\-\fR[\fInumber\fR][\fBlbc\fR][\fBf\fR]] [\fIfile\fR]
.br
\fBtail\fR [\fB+\fR/\fB\-\fR[\fInumber\fR][\fBl\fR][\fBr\fR]] [\fIfile\fR]
.br
\fBtail\fR [\fB\-f\fR] [\fB\-c\fI number\fR|\fB\-n\fI number\fR] [\fIfile\fR]
.SH DESCRIPTION
The
.B tail
command copies the named
.I file
to the standard output beginning at a designated place.
If no
.I file
is named,
the standard input is used.
.PP
Copying begins at distance \fB+\fInumber\fR from the beginning,
or \fB\-\fInumber\fR from the end of the input.
.I Number
is counted in units of lines, blocks or characters (i.\|e. bytes),
according to the appended option
.BR l ,
.B b
or
.BR c .
When no units are specified,
counting is by lines;
the default
.I number
is 10.
.PP
If the
.B f
(``follow'') option is present,
.B tail
will not terminate at end-of-file,
but check for further data to write every second.
.PP
With the
.B r
option,
the order of lines printed is reversed.
If no
.I number
is specified,
the entire file is printed.
.I Number
is always taken as count of lines from the end of input.
.PP
The
.B tail
command also accepts the following options
that were introduced by POSIX.2,
in the form shown in the third synopsis line:
.TP
\fB\-c\fR [\fB+\fR|\fB\-\fR]\fInumber\fR
Copying will start at
.I number
bytes;
if the option argument starts with a `\fB+\fR',
from the begin of the file,
with `\fB\-\fR'
or no sign from its end.
.TP
.B \-f
Follow file changes,
as described above.
.TP
\fB\-n\fR [\fB+\fR|\fB\-\fR]\fInumber\fR
Copying will start at
.I number
lines.
The meaning of the sign
is the same as for the
.B \-c
option.
.SH "SEE ALSO"
dd(1),
head(1)
.SH NOTES
Tails relative to the end of the file
are treasured up in a buffer,
and thus are limited in length.
Various kinds of anomalous behaviour
may happen with character special files.
