.\"
.\" Sccsid @(#)mesg.1	1.2 (gritter) 7/17/05
.\" Parts taken from mesg(1), Unix 7th edition:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.\"
.TH MESG 1 "7/17/05" "Heirloom Toolchest" "User Commands"
.SH NAME
mesg \- permit or deny messages
.SH SYNOPSIS
\fBmesg\fR [[\fB\-\fR](\fBy\fR|\fBn\fR)]
.SH DESCRIPTION
.I Mesg
with argument
.B n
forbids messages via
.IR  write (1)
by revoking non-user
write permission on the user's terminal.
.I Mesg
with argument
.B y
reinstates permission.
All by itself,
.I mesg
reports the current state without changing it.
.SH FILES
/dev/tty*
.br
/dev
.SH "SEE ALSO"
write(1)
.SH DIAGNOSTICS
Exit status is 0 if messages are receivable,
1 if not, 2 on error.
