.\"
.\" Sccsid @(#)uptime.1	1.5 (gritter) 4/17/03
.\" partially derived from 4.2BSD's uptime(1)
.\" Copyright (c) 2003 Gunnar Ritter
.\"
.\" SPDX-Licence-Identifier: Zlib
.\"
.TH UPTIME 1 "4/17/03" "Heirloom Toolchest" "User Commands"
.SH NAME
uptime \- show how long system has been up
.SH SYNOPSIS
uptime
.SH DESCRIPTION
Uptime prints the current time,
the length of time the system has been up,
and the average number of jobs in the run queue
over the last 1, 5 and 15 minutes.
It is, essentially, the first line of a
.IR w (1)
command.
.SH FILES
.TP
.B /proc
list of processes
.TP
.B /var/run/utmp
list of active logins
.SH "SEE ALSO"
w(1),
proc(5),
utmp(5)
