.\"
.\" Sccsid @(#)pwd.1	1.2 (gritter) 6/29/05
.\" Derived from pwd(1), Unix 7th Edition:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.\"
.TH PWD 1 "6/29/05" "Heirloom Toolchest" "User Commands"
.SH NAME
pwd \- working directory name
.SH SYNOPSIS
.B pwd
.SH DESCRIPTION
.I Pwd
prints the pathname of the working (current) directory.
.SH "SEE ALSO"
sh(1)
