.\"
.\" SPDX-Licence-Identifier: CDDL-1.0
.\"
.\" Copyright (c) 2005 Gunnar Ritter, Freiburg i. Br., Germany.
.\"
.\" Sccsid @(#)getopt.1	1.2 (gritter) 6/24/05
.TH GETOPT 1 "6/24/05" "Heirloom Toolchest" "User Commands"
.SH NAME
getopt \- parse command options
.SH SYNOPSIS
set \-\- \`\fBgetopt\fP \fIoptstring\fP $*\`
.SH DESCRIPTION
.I getopt
rearranges command options for shell scripts.
It accepts an
.I optstring
argument like
.IR getopt (3),
i.\|e. a list of characters (bytes)
where each character represents an option letter.
A character followed by
.B :
indicates that the option has an argument.
When an argument list is passed to
.IR getopt ,
it prints it such that
each option forms a separate argument,
with option and option argument separated by a space,
and a `\-\-' separates options and remaining non-option arguments.
For example, `getopt a:bc \-bc \-aarg'
results in the output `\-b \-c \-a arg \--'.
.SH "SEE ALSO"
sh(1)
.SH NOTES
.I getopt
cannot handle arguments that contain white space.
For this reason,
the shell special command
.I getopts
is preferred over
.IR getopt .
