.\"
.\" Derived from uniq(1), Unix 32V:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.\"
.TH UNIQ 1 "12/6/04" "Heirloom Toolchest" "User Commands"
.SH NAME
uniq \- report repeated lines in a file
.SH SYNOPSIS
.HP
.ad l
.nh
\fBuniq\fR [\fB\-udc\fR]
[\fB\-f\ \fIfields\fR]
[\fB\-s\ \fIletters\fR]
[\fB+\fIletters\fR] [\fB\-\fIfields\fR]
[\fIinput\fR\ [\fIoutput\fR]]
.br
.ad b
.SH DESCRIPTION
.I Uniq
reads the input
file comparing adjacent lines.
In the normal case, the second and succeeding copies
of repeated lines are
removed; the remainder is written on the output file.
Note that repeated lines must be adjacent
in order to be found;
see
.IR  sort (1).
If the
.B \-u
flag is used,
just the lines that are not repeated
in the original file are output.
The
.B \-d
option specifies that
one copy of just the repeated lines is to
be written.
The normal mode output is the union of the
.B \-u
and
.B \-d
mode outputs.
.PP
The
.B \-c
option supersedes
.B \-u
and
.B \-d
and generates
an output report in default style
but with each line preceded by a count of the
number of times it occurred.
.PP
The
.I letters
and
.I chars
arguments specify skipping an initial portion of each line
in the comparison:
.TP 8
.BI \- n
The first
.IR n 
fields
together with any blanks before each are ignored.
A field is defined as a string of non-space, non-tab characters
separated by tabs and spaces from its neighbors.
.TP 8
\fB\-f\fI n\fR
Same as
\fB\-\fIn\fR.
This option was introduced by POSIX.2.
.TP 8
.BI + n
The first
.IR n 
characters are ignored.
Fields are skipped before characters.
.TP 8
\fB\-s\fI n\fR
Same as
\fB+\fIn\fR.
This option was introduced by POSIX.2.
.SH "ENVIRONMENT VARIABLES"
.TP
.BR LANG ", " LC_ALL
See
.IR locale (7).
.TP
.B LC_CTYPE
Determines the mapping of bytes to characters
and the set of blank characters.
.SH "SEE ALSO"
comm(1),
sort(1),
locale(7)
