.\"
.\" Copyright (c) 2003 Gunnar Ritter
.\"
.\" SPDX-Licence-Identifier: Zlib
.\"
.\" Sccsid @(#)news.1	1.4 (gritter) 4/17/03
.TH NEWS 1 "4/17/03" "Heirloom Toolchest" "User Commands"
.SH NAME
news \- print news items
.SH SYNOPSIS
\fBnews\fR [\fB\-a\fR] [\fB\-n\fR] [\fB\-s\fR] [\fIitems\fR]
.SH DESCRIPTION
The
.B news
command prints files from the systems news directory
that have been added or modified
since its previous invocation,
preceded by a header,
starting with the most recent file.
.PP
It accepts the following options:
.TP
.B \-a
Print all files in the system news directory.
The recorded time of the previous invocation is not changed.
.TP
.B \-n
Print only the names of added or modified files.
The recorded time of the previous invocation is not changed.
.TP
.B \-s
Print only the count of added or modified files.
The recorded time of the previous invocation is not changed.
.SH "ENVIRONMENT VARIABLES"
.TP
.B HOME
User's home directory.
.SH FILES
.TP
\fB$HOME/.news_time\fR
The time of the previous invocation is recorded
as the modification time of this file.
.TP
\fB/var/news\fR
System news directory.
