.\"
.\" Sccsid @(#)kill.1	1.2 (gritter) 6/30/05
.\" Derived from kill(1), Unix 7th edition:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.\"
.TH KILL 1 "6/30/05" "Heirloom Toolchest" "User Commands"
.SH NAME
kill \- terminate a process
.SH SYNOPSIS
\fBkill\fR [\fB\-\fIsignal\fR|\fB\-s\ \fIsignal\fR] \fIprocessid\fR ...
.br
\fBkill\fR \fB\-l\fR [\fIstatus\fR]
.SH DESCRIPTION
.I Kill
sends signal 15 (terminate) to the specified processes.
If a signal number or symbolic signal name preceded by `\-' or
.B \-s
is given as first argument, that signal is sent instead of
terminate
(see
.IR  signal (2)).
This will kill processes that do not catch the signal;
in particular `kill \-9 ...' is a sure kill.
.PP
By convention, if process number 0 is specified, all members
in the process group (i.e. processes resulting from
the current login) are signaled.
If process number \-1 is specified,
all processes for which the user is permitted to send a signal are signaled.
Otherwise if the process number is negative,
it is treated as a process group id,
and all processes in that group are signaled.
.PP
With the
.B \-l
option, all available symbolic signal names are listed.
If the
.I status
argument is present,
the symbolic signal name corresponding to
.IR status ,
interpreted either as a signal number or as an exit value
as given by the `$?' shell parameter,
is printed.
.PP
A symbolic signal name consists of the name of the signal
in the `C' language without the `SIG' prefix,
e.\|g. `QUIT' for `SIGQUIT'.
.PP
The killed processes must belong
to the current user unless
he is the super-user.
.PP
The process number of an asynchronous process
started with `&' is reported by the shell.
Process numbers can also be found by using
.IR ps (1).
.SH "SEE ALSO"
ps(1), kill(2), signal(2)
