.\"
.\" Sccsid @(#)nohup.1	1.6 (gritter) 1/24/05
.\" Parts taken from nice(1), Unix 7th edition:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.\"
.TH NOHUP 1 "1/24/05" "Heirloom Toolchest" "User Commands"
.SH NAME
nohup \- run a command immune to hangups
.SH SYNOPSIS
\fBnohup\fI utility \fR[\fIarguments\fR\ ...]
.SH DESCRIPTION
The
.B nohup
command executes
.I utility
immune to hangup signals,
and, for
.B /usr/5bin/nohup
and
.BR /usr/5bin/s42/nohup ,
also immune to quit signals.
If standard output is not re-directed by the user to a non-tty file,
it will be appended to the file `\fInohup.out\fR'.
If \fInohup.out\fR is not writable
in the current directory,
output is appended to
.IR $HOME/nohup.out .
If these files do not exist,
they are created with mode 666 for
.B /usr/5bin/nohup
and
.B /usr/5bin/s42/nohup
or with mode 600 for
.B /usr/5bin/posix/nohup
and
.BR /usr/5bin/posix2001/nohup .
If standard error is not re-directed by the user to a non-tty file,
it will be sent to the same file as standard output.
.SH "ENVIRONMENT VARIABLES"
.TP
.B PATH
Used to locate
.IR utility .
.SH "SEE ALSO"
chmod(1),
nice(1),
sh(1),
signal(2),
execvp(3),
isatty(3)
