.\"
.\" Sccsid @(#)calendar.1	1.7 (gritter) 10/11/03
.\"
.\" Derived from calendar(1), Unix 32V:
.\"
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.TH CALENDAR 1 "10/11/03" "Heirloom Toolchest" "User Commands"
.SH NAME
calendar \- reminder service
.SH SYNOPSIS
\fBcalendar\fR [\fB\-\fR]
.SH DESCRIPTION
.I Calendar 
consults the file `calendar' in the current directory
and prints out lines that contain today's or
tomorrow's date anywhere in the line.
In the C locale,
most reasonable month-day dates such as `Dec. 7,'
`december 7,' `12/7,' etc., are recognized, but not
`7 December' or `7/12'.
On weekends `tomorrow' extends through Monday.
.PP
When 
an argument is present,
.I calendar
does its job for every user
who has a file `calendar' in his login directory
and sends him any positive results by
.IR mail (1).
This can be done daily in the wee hours under control of
.IR cron (1).
.SH "ENVIRONMENT VARIABLES"
.TP 
.BR LANG ,\  LC_ALL
See locale(7).
.TP 
.B LC_CTYPE
Used to separate the first three characters
for abbreviated month names.
.TP 
.B LC_TIME
Determines the abbreviated month names
and the order of month and day.
.SH FILES
calendar
.br
/usr/5lib/calprog to figure out today's and tomorrow's dates
.br
/etc/passwd
.br
/tmp/cal*
.br
egrep, sed, mail subprocesses
.SH "SEE ALSO"
at(1),
cron(1),
mail(1)
.SH NOTES
Your calendar must be public information for you
to get reminder service.
.br
.I Calendar's
extended idea of `tomorrow' doesn't account for
holidays.
