.\"
.\" Sccsid @(#)tee.1	1.3 (gritter) 1/11/03
.\" Parts taken from tee(1), Unix 7th edition:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.\"
.TH TEE 1 "1/11/03" "Heirloom Toolchest" "User Commands"
.SH NAME
tee \- pipe fitting
.SH SYNOPSIS
\fBtee\fR [\fB\-ai\fR] [\fIfile\fR\ ...]
.SH DESCRIPTION
The
.B tee
command transcribes the standard input
to the standard output
and makes a copy in each
.IR file .
.PP
It accepts the following options:
.TP
.B \-a
Causes the output to be appended to the files
rather than overwriting them.
.TP
.B \-i
The
.B tee
command will ignore interrupts with this option.
.SH "SEE ALSO"
cat(1)
