.\"
.\" Copyright (c) 2003 Gunnar Ritter
.\"
.\" SPDX-Licence-Identifier: Zlib
.\"
.\" Sccsid @(#)listusers.1	1.6 (gritter) 4/17/03
.TH LISTUSERS 1 "4/17/03" "Heirloom Toolchest" "User Commands"
.SH NAME
listusers \- print a list of user logins
.SH SYNOPSIS
listusers [-g groups] [-l logins]
.SH DESCRIPTION
Listusers prints the name and the gecos information
of all users known to the system,
sorted by username.
.PP
Valid options are:
.TP
.BI "-g" \ groups
Only print the names of users
that belong to the given group.
Multiple groups are accepted if separated by commas.
.TP
.BI "-l" \ logins
Print only user names that match \fIlogins\fR.
Multiple user names are accepted if separated by commas.
.SH "SEE ALSO"
passwd(5)
.SH NOTES
Only users whose UID is greater than 100 are recognized.
