.\"
.\" Sccsid @(#)renice.1	1.8 (gritter) 12/6/04
.\"
.\"	from renice.8	6.2 (Berkeley) 5/19/86
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\" SPDX-Licence-Identifier: BSD-4-Clause-UC
.TH RENICE 1 "12/6/04" "Heirloom Toolchest" "User Commands"
.SH NAME
renice \- alter priority of running processes
.SH SYNOPSIS
\fBrenice\fR \fIpriority\fR
[[\fB\-p\fR] \fIpids\fR]
[[\fB\-g\fR] \fIpgrps\fR]
[[\fB\-u\fR] \fIusers\fR]
.sp
\fBrenice\fR [\fB\-n\fI increment\fR] [\fB\-g\fR|\fB\-p\fR|\fB\-u\fR] \fIID\fR
.SH DESCRIPTION
The
.B renice
command alters the scheduling priority
of one or more running processes.
The
.I ID
parameters are interpreted
as process IDs, process group IDs, or user names.
Renicing a process group causes all processes in the process group
to have their scheduling priority altered.
Renicing a user causes all processes owned by the user
to have their scheduling priority altered.
By default, the processes to be affected
are specified by their process IDs.
.PP
Users without appropriate privileges
may only alter the priority of processes they own,
and can only monotonically increase
their ``nice value'' within the range 0 to 19.
(This prevents overriding administrative fiats.)
Users with appropriate privileges
may alter the priority of any process
and set the priority to any value
in the range \-20 to 19.
Useful priorities are:
19 (the affected processes will run only
when nothing else in the system wants to),
0 (the ``base'' scheduling priority),
anything negative (to make things go very fast).
.PP
The
.B renice
command accepts the following options:
.TP
.B \-g
The following arguments will be interpreted
as process group IDs.
.TP
\fB\-n\fI increment\fR
Specifies the
.I increment
to add to the current priority
of the process with the highest priority
(lowest numerical value)
of the selection.
Without this option,
10 is used as increment.
.TP
.B \-p
The following arguments will be interpreted
as process IDs.
.TP
.B \-u
The following arguments will be interpreted
as user names or numerical user IDs.
.PP
In the first synopsis form,
.I priority
specifies the absolute value to set.
The default is 10.
If more than one of
.BR \-g ,
.B \-p
or
.B \-u
are given,
each option applies to the following arguments
until the next option is detected.
.PP
In the second synopsis form,
which was introduced by POSIX.2,
only one of
.BR \-g ,
.B \-p
or
.B \-u
may be given.
.SH "SEE ALSO"
nice(1),
priocntl(1),
getpriority(2),
setpriority(2)
