.\"
.\" SPDX-Licence-Identifier: CDDL-1.0
.\"
.\" Copyright (c) 2005 Gunnar Ritter, Freiburg i. Br., Germany.
.\"
.\" Sccsid @(#)mvdir.1	1.1 (gritter) 6/25/05
.TH MVDIR 1 "6/25/05" "Heirloom Toolchest" "User Commands"
.SH NAME
mvdir \- move a directory
.SH SYNOPSIS
\fBmvdir\fI source target\fR
.SH DESCRIPTION
The
.I mvdir
command moves the directory
.I source
to the directory
.IR target .
If
.I target
refers to an existing directory,
.I source
is moved into
.IR target ,
i.\|e. if
.I source
is `/path/to/last-component', it is moved to `\fItarget\fR/last-component'.
Otherwise,
.I target
must not previously exist.
.I source
is not allowed to be a sub-directory of
.I target
and vice-versa.
.SH "SEE ALSO"
mv(1)
