.\"
.\" SPDX-Licence-Identifier: CDDL-1.0
.\"
.\" Copyright (c) 2005 Gunnar Ritter, Freiburg i. Br., Germany.
.\"
.\" Sccsid @(#)dircmp.1	1.1 (gritter) 6/25/05
.TH DIRCMP 1 "6/25/05" "Heirloom Toolchest" "User Commands"
.SH NAME
dircmp \- directory comparison
.SH SYNOPSIS
\fBdircmp\fR [\fB\-ds\fR] [\fB\-w\fI width\fR] \fIdirectory directory\fR
.SH DESCRIPTION
The
.I dircmp
command creates a list of files which are 
identical, different, or exist in only one of the two
.I directories
given.
.PP
With the
.B \-d
option, differing files are compared using
.IR diff (1),
and its output is included.
.PP
The
.B \-s
option suppresses messages about identical files.
.PP
Output is paginated through
.IR pr (1).
The
.B \-w
option specifies a maximum
.I width
for the formatted output.
.SH "SEE ALSO"
diff(1)
.SH NOTES
.I dircmp
ignores files whose names contain backslash or newline characters.
