.\"
.\" Sccsid @(#)file.1	1.8 (gritter) 2/6/05
.\" Parts taken from file(1), Unix 7th edition:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.\"
.TH FILE 1 "2/6/05" "Heirloom Toolchest" "User Commands"
.SH NAME
file \- determine file type
.SH SYNOPSIS
\fBfile\fR [\fB\-h\fR] [\fB\-m\fI\ mfile\fR] [\fB\-f\fI\ ffile\fR] [\fB\-z\fR]
\fIarg\fR\ .\|.\|.
.br
\fBfile\fR [\fB\-h\fR] [\fB\-m\fI\ mfile\fR] [\fB\-z\fR] \-f\fI\ ffile\fR
.br
\fBfile\fR [\fB\-c\fR] [\fB\-m\fI\ mfile\fR]
.SH DESCRIPTION
.I File
performs a series of tests on each argument
in an attempt to classify it.
If an argument appears to be ascii,
.I file
examines the first 512 bytes
and tries to guess its language.
.PP
File formats identified by a magic number
(that is a defined value at a defined place of the file)
are detected using the definitions in a magic file
.RB ( /usr/5lib/magic " by default)."
.PP
The
.I file
command accepts the following options:
.TP
.B \-c
Complain about format errors in the magic file
and display a summary of the magic known after reading.
.TP
\fB\-f\fI\ ffile\fR
The file given contains the names of other files to be examined,
one file name per line.
.TP
.B \-h
Symbolic links are normally followed.
This option causes
.I file
not to follow symbolic links
but to print their target instead.
.TP
\fB\-m\fI\ mfile\fR
Use
.I mfile
instead of
.B /usr/5lib/magic
as the magic file.
.TP
.B \-z
If a file turns out to be compressed with
.IR compress (1),
.IR gzip (1),
or
.IR bzip2 (1),
do not further examine the file itself
but run the appropriate decompression program
and examine its output.
This option is an extension.
.SH FILES
/usr/5lib/magic
.SH "ENVIRONMENT VARIABLES"
.TP
.B SYSV3
Causes the text of some messages to be changed.
.SH NOTES
.I File
often makes mistakes.
In particular it often suggests that
command files are C programs.
.PP
.I File
does not currently accept the
.BR \-d ,
.BR \-i ,
\fB\-M \fIfile\fR,
and
\fB\-m \fIfile\fR
options from POSIX.1-2001.
