.\"
.\" Copyright (c) 2003 Gunnar Ritter
.\"
.\" SPDX-Licence-Identifier: Zlib
.\"
.\" Sccsid @(#)rmdir.1	1.7 (gritter) 12/1/03
.TH RMDIR 1 "12/1/03" "Heirloom Toolchest" "User Commands"
.SH NAME
rmdir \- remove directories
.SH SYNOPSIS
\fBrmdir\fR [\fB\-ps\fR] \fIdirname\fR ...
.SH DESCRIPTION
.B Rmdir
removes the entries for the named directories,
which must be empty.
.PP
It accepts the following options:
.TP
.B \-p
Remove the named directory
and all its named parent directories.
This is only successful
if each parent directory
contains only the specied subdirectories.
For
.B /usr/5bin/mkdir
and
.BR /usr/5bin/s42/mkdir ,
a message is printed
if the whole hierarchy was successfully removed.
.TP
.B \-s
Suppress error messages if
.B \-p
is in effect.
.SH "SEE ALSO"
mkdir(1),
rm(1),
rmdir(2)
.SH NOTES
