.\"
.\" Copyright (c) 2003 Gunnar Ritter
.\"
.\" SPDX-Licence-Identifier: Zlib
.\"
.\" Sccsid @(#)setpgrp.1	1.3 (gritter) 4/17/03
.TH SETPGRP 1 "4/17/03" "Heirloom Toolchest" "User Commands"
.SH NAME
setpgrp \- set process group ID and session ID
.SH SYNOPSIS
\fBsetpgrp\fI command\fR [\fIargument\fR\ ...]
.SH DESCRIPTION
If the
.B setpgrp
command is not already a session leader,
it will set its process group ID and session ID
to its process id
and release its controlling terminal.
In any case,
.I command
will be executed using the given
.IR arguments .
.SH "SEE ALSO"
setpgid(2),
setsid(2),
execvp(3)
