.\"
.\" Sccsid @(#)tsort.1	1.2 (gritter) 8/17/03
.\" Parts taken from tsort(1), Unix 32V:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera 
.\"
.TH TSORT 1 "8/17/03" "Heirloom Toolchest" "User Commands"
.SH NAME
tsort \- topological sort
.SH SYNOPSIS
\fBtsort\fR [\fIfile\fR]
.SH DESCRIPTION
.I Tsort
produces on the standard output a totally ordered list of items
consistent with a partial ordering of items
mentioned in the input
.IR file .
If no
.I file
is specified, the standard input is understood.
.PP
The input consists of pairs of items (nonempty strings)
separated by blanks.
Pairs of different items indicate ordering.
Pairs of identical items indicate presence, but not ordering.
.SH "SEE ALSO"
lorder(1)
.SH DIAGNOSTICS
Odd data: there is an odd number of fields in the input file.
.SH NOTES
Uses a quadratic algorithm;
not worth fixing for the typical use of ordering
a library archive file.
