.\"
.\" Copyright (c) 2003 Gunnar Ritter
.\"
.\" SPDX-Licence-Identifier: Zlib
.\"
.\" Sccsid @(#)line.1	1.4 (gritter) 4/17/03
.TH LINE 1 "4/17/03" "Heirloom Toolchest" "User Commands"
.SH NAME
line \- read one line
.SH SYNOPSIS
.B line
.SH DESCRIPTION
.I Line
copies one line from standard input to standard output.
If end-of-file is reached on input or if a read error occurs,
its exit status is non-zero.
.I Line
always writes a newline as the last character.
.SH "SEE ALSO"
read(1)
