.\"
.\" Sccsid @(#)tty.1	1.2 (gritter) 5/21/03
.\" Parts taken from tty(1), Unix 7th edition:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.\"
.TH TTY 1 "5/21/03" "Heirloom Toolchest" "User Commands"
.SH NAME
tty \- get terminal name
.SH SYNOPSIS
\fBtty\fR [\fB\-l\fR] [\fB\-s\fR]
.SH DESCRIPTION
.I Tty
prints the pathname of the user's terminal.
If the
.B \-s
option is present,
nothing is printed,
and only the exit status is affected.
With the
.B \-l
option,
.I tty
prints the line number
if standard input is connected to a synchronous line.
.SH DIAGNOSTICS
`not a tty' if the standard input file is not a terminal.
.PP
The exit status is
.TP 10
0
if standard input is a terminal;
.br
.ns
.TP 10
1
if standard input is not a terminal;
.br
.ns
.TP 10
2
or greater on error.
