.\"
.\" Copyright (c) 2003 Gunnar Ritter
.\"
.\" SPDX-Licence-Identifier: Zlib
.\"
.\" Sccsid @(#)dirname.1	1.2 (gritter) 4/17/03
.TH DIRNAME 1 "4/17/03" "Heirloom Toolchest" "User Commands"
.SH NAME
dirname \- return the directory portion of a pathname
.SH SYNOPSIS
\fBdirname\fR \fIpath\fR
.SH DESCRIPTION
.I Dirname
deletes the file part of the given
.I path
and prints the result,
or `.'
if no directory part is present.
.SH "SEE ALSO"
basename(1),
sh(1)
