.\"
.\" chroot.8 (takusuman) 7/2/22
.\" Derived from the chroot(8) present in Solaris 2.5, but rewritten from
.\" scratch.
.\" Copyright(C) 2021-2022 Pindorama. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Zlib
.TH CHMOD 8 "7/2/22" "Heirloom Toolchest" "User Commands"
.SH NAME
chroot \- change the root directory for a command
.SH SYNOPSIS
\fBchroot\fR \fInew root\fR \fIcommand\fR
.SH DESCRIPTION

.SH "SEE ALSO"
cd(1),
chroot(2)
