.\"
.\" Sccsid @(#)nice.1	1.7 (gritter) 12/6/04
.\" Parts taken from nice(1), Unix 7th edition:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" SPDX-Licence-Identifier: Caldera
.\"
.TH NICE 1 "12/6/04" "Heirloom Toolchest" "User Commands"
.SH NAME
nice \- run a command at low priority
.SH SYNOPSIS
\fBnice\fR [\fB\-n\fI number\fR] \fIutility\fR [\fIargument\fR ...]
.sp
\fBnice\fR [\fB\-\fInumber\fR] \fIutility\fR [\fIargument\fR ...]
.SH DESCRIPTION
The
.B nice
command
executes
.I utility
with low scheduling priority.
If the
.I number
argument
is present,
the priority is incremented
(higher numbers mean lower priority)
by that amount up to a limit of 19.
The default number is 10.
.PP
An user with appropriate privileges
may run commands with priority higher than normal
by using a negative priority,
e.\ g. `\fI\-\-10\fR'.
.PP
The \fI\-n\ number\fR syntax was introduced by POSIX.2.
.SH "ENVIRONMENT VARIABLES"
.TP
.B PATH
Used to locate
.IR utility .
.SH "SEE ALSO"
priocntl(1),
sh(1),
nice(2),
execvp(3)
